baseURL = "https://osakacycling.netlify.app/"
languageCode = "en-us"
title = "Osaka Cycling"
theme = "ananke"

[params]
Description = "Cycling, outdoor spots in/around Osaka."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
