baseURL = "https://osakacycling.netlify.app/"
languageCode = "en-us"
title = "Osaka Cycling"
theme = "ananke"

[params]
Description = "Cycling, outdoor spots in/around Osaka."

[markup]
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    [markup.goldmark.parser.attribute]
      block = true
      title = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
